---
name: Image Promotion
description: Promote a tagged image to a deployment repo using Kustomize and Git
inputs:
  git-commit-user:
    description: Name to add to the Git Commit Message
    required: false
    default: Kustomize Everything
  git-commit-email:
    description: Email to add to the Git Commit Message
    required: false
    default: kustomize-everything@users.noreply.github.com
  git-commit-message:
    description: Commit message to use for deployment
    required: false
  github-token:
    description: |
      GitHub token for either opening pull requests or fetching metadata about
      what is being promoted.
    required: true
  image-name:
    description: The name of the image
    required: false
  image-tag:
    description: The tag to promote
    required: false
  image-name-tag:
    description: The image name:tag to promote
    required: false
  image-additional-tags:
    description: Additional tags
    default: None
    required: false
  promotion-method:
    description: |
      How to handle the promotion. pull_request opens a PR against the
      repository, ensures that all checks pass on the PR, and then
      self-merges the PR. push will push the changes directly to the target
      branch.
    required: false
    default: push
  sha256-checksum:
    description: Checksum of Kustomize version
    required: false
    default: bba81aa61dba057db1d5abeddf1e522b568b2d906ab67a5c80935e97302c8773
  ssh-key:
    description: |
      SSH key for doing the promotion into the deployment repository.
      REMEMBER TO USE A GITHUB SECRET FOR THIS.
    required: true
  target-repo:
    description: The repo where the image promotion should be pushed
    required: true
  target-branch:
    description: |
      The branch where the image promotion should be pushed (defaults to main)
    default: main
    required: false
  target-dir:
    description: The directory where the kustomize.yaml to update is located in
      the target-repo
    required: true
  version:
    description: Version of Kustomize to use
    required: false
    default: 4.5.5
  working-directory:
    description: |
      Working directory where the deployment repo should be checked out into
    required: false
    default: image-promotion
outputs:
  deployment-repo-sha:
    description: "Git SHA of promotion commit on deployment repo"
    value: ${{ steps.update-image-tag.outputs.deployment-repo-sha }}
  deployment-repo-sha-url:
    description: "Github URL for the promotion commit on the deployment URL"
    value: ${{ steps.update-image-tag.outputs.deployment-repo-sha-url }}
  deployment-repo-sha-short:
    description: "Git short SHA of promotion commit on deployment repo."
    value: ${{ steps.update-image-tag.outputs.deployment-repo-sha-short }}
  image-name-tag:
    description: "Combined image name:tag that was promoted"
    value: ${{ steps.update-image-tag.outputs.image-name-tag }}
  image-tags:
    description: "Additional tags that were provided"
    value: ${{ steps.update-image-tag.outputs.image-additional-tags }}

runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.target-repo }}
        ref: ${{ inputs.target-branch }}
        ssh-key: ${{ inputs.ssh-key }}
        path: ${{ inputs.working-directory }}

    - name: GitHub Metadata
      uses: kustomize-everything/action-github-metadata@v1.0.0

    - name: Kustomize Setup
      uses: kustomize-everything/action-kustomize@v1.0.4
      with:
        version: ${{ inputs.version }}
        sha256-checksum: ${{ inputs.sha256-checksum }}

    - name: Set Git Author
      shell: bash
      run: |
        git config --global user.name ${{ inputs.git-commit-user }}
        git config --global user.email ${{ inputs.git-commit-email }}

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Update Image Tag in Base
      id: update-image-tag
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        IMAGE_ADDITIONAL_TAGS: ${{inputs.image-additional-tags}}
        IMAGE_NAME_TAG: ${{inputs.image-name-tag}}
        IMAGE_NAME: ${{inputs.image-name}}
        IMAGE_TAG: ${{inputs.image-tag}}
        PROMOTION_METHOD: ${{ inputs.promotion-method }}
        TARGET_BRANCH: ${{ inputs.target-branch }}
        TARGET_DIR: ${{ inputs.target-dir }}
        TARGET_REPO: ${{ inputs.target-repo }}
      run: update-image-tag.sh
